---
name: Template-Patch
version: 0.03
author:
  - 'Gaal Yahas <gaal@forum2.org>'
abstract: Apply parameterized patches
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Template: 0
  Template::Extract: 0
build_requires:
  Class::Accessor::Ref: 0
  Test::Exception: 0
  Test::More: 0
provides:
  Template::Patch:
    file: lib/Template/Patch.pm
    version: 0.03
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
