---
name: Template-Patch
version: 0.02
author:
  - 'Gaal Yahas <gaal@forum2.org>'
abstract: Apply parameterized patches
license: perl
requires:
  Template: 0
  Template::Extract: 0
build_requires:
  Test::Exception: 0
  Test::More: 0
provides:
  Template::Patch:
    file: lib/Template/Patch.pm
    version: 0.02
generated_by: Module::Build version 0.26
